version: '3.8'
services:
  flask:
    build: .
    container_name: nuozhadu
    ports:
      - "8990:8990"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - host.docker.internal:host-gateway
